### ISSUE TITLE
I'm getting this error when I enter the path to my windows kit bin folder

### ISSUE THREAD

**Issue by DM164** [felixrieseberg/electron-windows-store#124]
? Please enter the location of your Windows Kit's bin folder:  "C:\Program Files (x86)\Windows Kits\8.1\bin\x64"
Creating Certficate
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at inquirer.prompt.then (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-windows-store\lib\setup.js:173:31)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at inquirer.prompt.then (C:\Users\denis\AppData\Roaming\npm\node_modules\electron-windows-store\lib\setup.js:173:31)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by DM164** [comment]
Nevermind I solved the issue.

**Comment by mark-wallpapermatic** [comment]
@DM164 How did you resolve this?

> Nevermind I solved the issue.

**Comment by hoangdung-qbt** [comment]
@DM164 : Ciao! I just ran into this issue too.  How did you resolve it? Thanks!

**Comment by Stanlyhalo** [comment]
How are you guys solving it?

**Comment by Ali-Albaker** [comment]
I am getting the same issue can you please advise how you resolved this issue?

**Comment by RGBNu** [comment]
For those running into this error. It's not actually the step of entering the Windows Kit bin folder that is causing the error. The complaint is actually the step before. When you're asked to enter your Publisher Identity, don't just put in your company name or whatever. You need to use the format specified in the suggestiion (CN=developmentca).  So for example instead of entering MyCompany, put in CN=MyCompany. At least that's how I got past this error.

**Comment by arepp23** [comment]
I'm seeing the same error even when I specify the publisher identity with an `=` like `CN=DBSDev`
