### ISSUE TITLE
developer certificate

### ISSUE THREAD

**Issue by lauer3912** [felixrieseberg/electron-windows-store#28]
@felixrieseberg Hello, please tell us about the developer certificate to obtain and how to generate devcert.pfx

**Comment by felixrieseberg** [comment]
We're working with a few selected companies right now to iron out the edges, but submission should be available "soon". We still don't have a date yet, but as soon as we do, I'll make sure to let people know!

So, for now, you can use any developer certificate (as long as it's installed on the target machine). Once submission works, you should use your Windows Developer Account certificate.

**Comment by rjakobsson** [comment]
Hi. Sorry for digging up this old ticket, but I have the same question. Where can one obtain a developer certificate to use for submission to the Windows Store?

**Comment by miloszfalinski** [comment]
@felixrieseberg Any updates on this? Is this project dead or in limbo? Still trying to figure out how to sign and submit my app to the Windows Store.

**Comment by felixrieseberg** [comment]
Hey! No, this project is totally alive - but you might want to head over to https://developer.microsoft.com/en-us/windows/projects/campaigns/desktop-bridge to sign up.

**Comment by rjakobsson** [comment]
I can't find out how to do this. @felixrieseberg do you have a URL to the page where I can read about how to obtain and install a certificate? My company has the $99 Dev Center subscription. I'm totally lost in this Windows world. Coming from macOS, iOS and Android. Thanks!

**Comment by rjakobsson** [comment]
Do I need to buy a certificate from outside of the Windows portal, say via Symantec or anything like that?

**Comment by miloszfalinski** [comment]
@rjakobsson Yes, you'll need an external certificate.

@felixrieseberg I would also like to get some more information on this process. 

Here's a snippet that I came up with by trial/error in order to convert and sign the app:

```
electron-windows-store --input-directory C:\Users\m\Documents\app --output-directory C:\Users\m\Documents\output\app --flatten true --package-version 1.2.2.0 --package-background-color "#0086c7" --package-name app --assets C:\Users\m\Documents\assets --dev-cert C:\Users\m\Documents\devcert.pfx --publisher="CN=Name, O=Name, L=Town, S=State, C=GB" --signtool-params "-p","a","-t","http://timestamp.digicert.com"
```

I still get some errors on the Windows Dev portal so it'd really help if this was documented somehow.

**Comment by felixrieseberg** [comment]
Hey - just to follow up: You will currently need to *apply* to distribute the app via the Windows Store. However, any app with a valid developer certificate (valid as in trusted by Windows) can be installed by users with a fancy double click.

I'm sorry that I don't have more information - I joined Slack a few weeks ago, meaning that I'm a bit out of the loop, but that's the current status. I'd just go with the self-download method until Microsoft is ready to open the flood gates 🏄

**Comment by stefanhuber** [comment]
ok. I have a developer certificate, which was created by the electron-windows-store command. If I want to install the appx on other windows 10 machines, the installer tells me, that the certificate is not trusted (no trusted root certificate). Can I sign the developer certificate somehow with a root certificate? Otherwise my developer certificate needs to be installed before the appx can be installed, which is not a good approach...

**Comment by miloszfalinski** [comment]
@stefanhuber To submit to Windows Store, this certificate is enough. Windows Store folks will sign you app after you submit (if you are in the Desktop Bridge program) and you won't be able to distribute or use the Windows Store build before that. 

You only need a proper app signing certificate (eg from Digicert) if you plan to distribute the application by sending or selling the Appx file yourself.  Otherwise the app that will go into Windows Store does not require a proper certificate, the dummy one is enough. 

We somehow got into the Bridge program a couple months ago and have our Electron app in the store now. However I'm not sure how to find the program again - it could be this: https://developer.microsoft.com/en-us/windows/projects/campaigns/desktop-bridge More details here: https://blogs.msdn.microsoft.com/appconsult/2016/10/13/desktop-bridge-the-bridge-between-win32-apps-and-the-universal-windows-platform/

**Comment by stefanhuber** [comment]
Thank you for your answer!

I registered for this desktop-bridge, however the response was always recognized as spam... Therefore I thought they rejected my submission.

Do you still remember how long it took until Microsoft enabled this desktop bridge for your developer account?

**Comment by miloszfalinski** [comment]
@stefanhuber Same thing - also spam! We were approved within a couple of weeks after we replied. It took around 3 weeks total with preparing the app itself, as it needed a custom manifest file, but they provided good technical support for us.
