### ISSUE TITLE
publisherName must be a string

### ISSUE THREAD

**Issue by MehediH** [felixrieseberg/electron-windows-store#73]
I am trying to create a certificate for my app, but I am getting an error saying publisherName must be a string :/ 

![image](https://cloud.githubusercontent.com/assets/10274434/24521267/6ffb1c9c-1583-11e7-9d33-be39a60b9b44.png)

Any idea what's causing this? This tool worked nicely for me in the past with the same app.

**Comment by felixrieseberg** [comment]
Thanks for the report, it seems like @jacobq's last PR broke something. Feel free to install the last version (0.9.3), I'll try to figure out what broke.

**Comment by jacobq** [comment]
I think it might be a `publisher` vs `publisherName` naming goof in my commit. 
https://github.com/felixrieseberg/electron-windows-store/commit/2130d97b9b4188e0f684f9822d257143b602b2b1#diff-3dc8020b53daf52d9c95dc37e8688b10R60

**Comment by MehediH** [comment]
Thanks guys! I am now getting this error, pretty sure this isn't related to this package but not sure how to fix this, couldn't find much details online either 
![image](https://cloud.githubusercontent.com/assets/10274434/24526317/a2791de2-1595-11e7-9df8-868533e3a9be.png)

**Comment by jacobq** [comment]
@MehediH It looks like there's a [`"` character in your path](http://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names#1976050)?

P.S. In the future if you could copy & paste the text instead of just a screenshot that would be more useful (avoids size/scaling problems on different screens, shows more text that just what's in the window, etc., as well as more search-friendly for other people who might be running into the same problem).

**Comment by MehediH** [comment]
@jacobq Will make sure to copy paste next time. 

There isn't any electron-windows-store folder in my AppData folder for some reason, I looked into the npm folder but couldn't find anything.

**Comment by jacobq** [comment]
According to the screenshot above it was apparently in `C:\Users\mehed\AppData\Roaming\npm\node_modules\electron-windows-store` (probably from `npm install -g ...`) If you copy and paste that into Windows Explorer do you encounter an error?

**Comment by MehediH** [comment]
Nope, but I don't see the `E9C87844-1C8E-430E-9950-8E0DC3A6EE56"` folder there

**Comment by jacobq** [comment]
That may be because that's not a valid file name ;)
Could you paste the config file or command line arguments you're passing? I have no idea where that crazy name is coming from unless you entered it.

**Comment by MehediH** [comment]
Here you go, removed my publisher details for obvious reasons :)

`electron-windows-store --input-directory .\build --output-directory .\output\ --flatten true --package-version 1.0.0.0 --publisher "CN=pub_id_here" --package-name Tweeten.TweetenApp --package-display-name Tweeten --package-description "Tweeten, an app that makes TweetDeck prettier." --package-executable app\tweeten.exe --assets .\assets -m appxmanifest.xml`

**Comment by jacobq** [comment]
@MehediH Unfortunately, I think the problem is in your publisher string, so if you're [not comfortable sharing it](https://stackoverflow.com/questions/18755225/does-your-microsoft-publisher-id-have-to-be-kept-private) I guess the best advice I can give you is look at it closely. Does it contain quotation marks? If so, try escaping them or removing the surrounding quotes.

**Comment by MehediH** [comment]
Hmm thanks anyway, @jacobq!
